# Generated by Django 5.0.14 on 2026-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('monthly_travelers', models.PositiveIntegerField(blank=True, null=True)),
                ('service_needs', models.CharField(choices=[('Managed Corporate Travel', 'Managed Corporate Travel'), ('Executive & VIP Travel', 'Executive & VIP Travel'), ('Conference & Event Travel', 'Conference & Event Travel'), ('Group & Project Travel', 'Group & Project Travel'), ('Travel Policy & Cost Optimization', 'Travel Policy & Cost Optimization'), ('Other', 'Other')], max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
