# Generated by Django 5.0.14 on 2026-02-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_package_is_featured'),
        ('users', '0002_corporateinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageQuoteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('package_slug', models.CharField(blank=True, default='', max_length=220)),
                ('package_location', models.CharField(blank=True, default='', max_length=150)),
                ('package_duration', models.CharField(blank=True, default='', max_length=100)),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, default='', max_length=120)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_inquiries', to='adminside.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
