# Generated by Django 5.0.14 on 2026-02-05 19:31

import django.db.models.deletion
from django.db import migrations, models


def migrate_package_json(apps, schema_editor):
    Package = apps.get_model("adminside", "Package")
    PackageFeature = apps.get_model("adminside", "PackageFeature")
    PackageItineraryDay = apps.get_model("adminside", "PackageItineraryDay")

    for package in Package.objects.all():
        features = getattr(package, "features", []) or []
        itinerary = getattr(package, "itinerary", []) or []

        for index, feature in enumerate(features, start=1):
            PackageFeature.objects.create(
                package=package,
                text=str(feature),
                sort_order=index,
            )

        for index, item in enumerate(itinerary, start=1):
            if isinstance(item, dict):
                day_number = item.get("day", index)
                title = item.get("title", "")
                description = item.get("description", "")
            else:
                day_number = index
                title = str(item)
                description = ""
            PackageItineraryDay.objects.create(
                package=package,
                day_number=day_number or index,
                title=str(title),
                description=str(description),
                sort_order=index,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_package_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='adminside.package')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('inclusions', models.TextField(blank=True, default='')),
                ('exclusions', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='adminside.package')),
            ],
            options={
                'ordering': ['sort_order', 'day_number', 'id'],
            },
        ),
        migrations.RunPython(migrate_package_json, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.RemoveField(
            model_name='package',
            name='itinerary',
        ),
    ]
