# Generated by Django 5.0.14 on 2026-02-03 12:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=25, unique=True),
        ),
    ]
